traefik:
  middlewares:
    # NOTE: middleware name
    # A lowercase RFC 1123 subdomain must consist of lower
    # case alphanumeric characters, '-' or '.', and must start
    # and end with an alphanumeric character.
    redirections:
      withclustername:
        permanent: false
        regex: apps.${cluster_info.base_domain}
        replacement: apps.${cluster_info.cluster_name}.${cluster_info.base_domain}
